# First section for the main introduction page

# Main menu section
[[pages]]
name = "Main menu"
icon = ""
is_section = true

# Introduction section

[[pages]]
path = "app_pages/1_Introduction.py"
name = "Introduction"
icon = "ğŸŒ"

[[pages]]
path = "app_pages/descriptive_statistics.py"
name = "Descriptive Statistics"
icon = "ğŸ“ˆ"

# Visualizations section

[[pages]]
path = "app_pages/2_Visualization.py"
name = "Food Prices Visualization"
icon = "ğŸ“Š"

# Conclusions section

[[pages]]
path = "app_pages/3_Conclusions.py"
name = "Conclusions"
icon = "ğŸ“"
